root: ./

structure:
  readme: README.md
  summary: CONTENTS.md

redirects:
  general/communication: ./general/communication.md
  general/project-process: ./general/project-process.md
  management/cooperation: ./management/cooperation.md
  management/agile-scrum: ./management/agile-scrum.md
  dev/api: ./dev/api.md
  dev/clean-code: ./dev/clean-code.md
  devops/ci-cd: ./devops/ci-cd.md
