root: ./

structure:
  readme: README.md
  summary: CONTENTS.md

redirects:
  salse/sales-process: ./salse/sales-process.md
  reqs/reqs-engineering: ./reqs/reqs-engineering.md
  ui-ux/principles: ./ui-ux/principles.md
  dev/tests: ./dev/tests.md
  devops/ci-cd: ./devops/ci-cd.md
